apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/bash", "-c", "echo $MYVAR > /opt/myvar; echo $OTRA > /opt/otra; echo $NEW > /opt/new"]
    env:
    - name: NEW
      valueFrom:
        secretKeyRef:
          name: secret-2
          key: NEW
    envFrom:
    - secretRef:
        name: secret-app
    - configMapRef:
        name: configmap-app
    volumeMounts:
    - name: vol
      mountPath: /opt/
  volumes:
  - name: vol
    hostPath:
      path: /opt/

# previous run
# k create cm configmap-app --from-literal=OTRA=otravariable
# k create secret generic secret-app --from-literal=MYVAR=myvariable
# k create secret generic secret-2 --from-literal=NEW=new