apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /opt/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/bash", "-c", "mkdir /opt/newdirectory"]
    volumeMounts:
      - mountPath: /opt/
        name: my-vol
  volumes:
  - name: my-vol
    persistentVolumeClaim:
      claimName: pvc