apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  restartPolicy: Never
  containers:
  - image: nginx
    name: nginx-container
    command: ["/bin/sh", "-c", "while true; do echo hello >> /opt/hello.txt ; sleep 10; done"]
    readinessProbe:
      exec:
        command:
          - cat
          - /opt/hello.txt
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 8
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /opt
      type: Directory

