apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
    app: App1
    function: Front-end
  annotations:
    buildversion: "1.34"      # Adding information
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1					      # must match with template label
  template:
    metadata:
      labels:
        app: App1				      # must match with selector label (match label)
        function: Front-ed
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp