#####################
# HEADLESS SERVICES #
#####################
# Is created like a common service
# It does not do load balancing
# It creates a dns for each pod in the form of podname.headless-servicename.namespace.svc.cluster.domain.example
# To create:


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
  subdomain: mysql-h		# both are required to create the dns
  hostname: mysql-pod
