apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
  namespace: dev  # add a namespace
spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl apply -f pod-definition.yml