# Set Node Affinity to the deployment to place the pods on node01 only

apiVersion: apps/v1
kind: Deployment
metadata:
 name: blue
spec:
  template:
    metadata:
      name: blue-pod
      labels:
        type: blue-pod
    spec:
      containers:
      - name: blue-pod
        image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - blue
  replicas: 3
  selector:
    matchLabels:
      type: blue-pod
