apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    resources:      # Resources
      requests:
        memory: "1Gi"
        cpu: 1
      limits:       # pods can use resources indefinitely, you can limit that using limits
        memory: "2Gi"
        cpu: 2