apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: simple-app
    type: python-app
spec:
  template:
    metadata:
      name: simple-app
      labels:
        app: simple-app
        type: python-app
    spec:
      containers:
      - name: simple-app
        image: fabenavideso/simple-app
  replicas: 10
  selector:
    matchLabels:
      type: python-app # to filter the pods to be controlled by this replicaset
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80  # port exposed on cloud loadbalancer
      targetPort: 8080  # pod port
  selector:
    app: simple-app  # should match with labels on pod
