apiVersion: apps/v1
kind: Deployment 
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:  
    metadata:
      labels: 
        app: api
    spec:
      containers:
        - name: api
          image: fabenavideso/simple-webapp:1.0.0-api
          ports: 
            - containerPort: 5000           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "apidb"            
            - name: DB_USERNAME
              value: "root"     
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-secret
                  key: db-password           
