apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  type: ClusterIP