apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2

# 0.1 CPU is the minimum
# 1G = 1.000.000.000 bytes
# 1Gi = 1.073.741.824 bytes
# a limit can be specified for each container on the pod
