---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc.gp2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi