# This pod will run its code and then terminate
# k8s will try to restart the pod again and again 
---
apiVersion: v1
kind: Pod
metadata:
  name: write-hola-mundo
spec:
  containers:
  - image: nginx
    name: alpine
    command: ["/bin/bash", "-c"]
    args: ["echo 'hola mundo' >> /opt/hola.txt"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc.gp2