apiVersion: v1
kind: Pod
metadata:
  name: simple-secret
  labels:
    app: myapp
spec:
  containers:
  - name: secret-handler
    image: nginx
    volumeMounts:
      - mountPath: /tmp/secret
        name: secret-volume
  volumes:
  - name: secret-volume
    secret: 
      secretName: app-secret-mount
