apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    app: myapp
spec:
  containers:
  - name: secret-handler
    image: bash:5.0.11
    args: ['bash', '-C', 'sleep 2d']
    volumeMounts:
      - mountPath: /tmp/secret
        name: secret-volume
  volumes:
  - name: secret-volume
    secret: 
      secretName: app-secret-mount
