apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  APP_COLOR: Ymx1ZQ==   # Base64 encoding
  APP_MODE: cHJvZA==    # Base64 encoding

#  echo -n 'blue' | base64 -> Ymx1ZQ== 
#  echo -n 'prod' | base64 -> cHJvZA== 

# echo -n 'Ymx1ZQ==' | base64 --decode  -> blue
# echo -n 'cHJvZA==' | base64 --decode  -> prod