apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end   # must match with the pod definition
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      serviceAccount: service-account-name
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: 50Mi
            cpu: 2
          requests:
            memory: 20Mi
            cpu: 1
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
  replicas: 3
  selector:
    matchLabels:
      type: front-end # to filter the pods to be controlled by this replicaset

# kubectl get all
