# in the case of kubernetes when the container finish it is restarted because k8s was designed to run the containers forever. 
# This is configured on the restart policy that is by default always.
apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-pod
spec:
  template:
    spec:
      containers:
      - name: math-pod
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never					# to never restart a pod that finish