apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
  nodeSelector:
    size: Large

# on node a label should be created
# kubectl label nodes node-1 size=Large
