apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    store: 1Gi
  hostPath:
    path: /tmp/data
  awsElasticBlockStore:
    volumeID: <VOLUME-ID>
    fsType: ext4