# The persistent volume is a cluster of volumes that applications can use
# It shouldn't be use on prod environment
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    store: 1Gi
  hostPath:     # not recommended for production environments
    path: /tmp/data