apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    env:
      - name: HELLO
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: HELLO          