# point to be used inside to communicate layers ex: frontend with backend
# A single interface to group pods on the backend

apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80  # port on backend (group of pods)
      port: 80        # port on service

  selector:
    app: myapp
    type: back-end  # should match with labels on pod  
