## It only works on cloud
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80  # port exposed on cloud loadbalancer
      targetPort: 8080  # pod port
  selector:
    app: myapp  # should match with labels on pod
